seed: 1234
workers: 0
#wandb:
#  project: sandbox
#  offline: False

#### Imputation params ########################################################
p_fault: 0.0015
p_noise: 0.05
in_sample: False

whiten_prob: 0.05
prediction_loss_weight: 1.0
impute_only_missing: False
warm_up_steps: 0

#### Dataset params ###########################################################
# dataset:
#    name: la
#    root_dir: '../../data/MetrLA'
#    splitting:
#      val_len: 0.1
#      test_len: 0.2
#    connectivity:
#      method: distance
#      threshold: 0.1
#      include_self: False
#      layout: edge_index
  
dataset:    
    name: climateHourly    # climateHourly
    root_dir: '../../data/NASA_data'
    splitting:
      val_len: 0.1
      test_len: 0.2
    connectivity:
        method: 'full'
      # threshold: 0.1
      # include_self: False
        layout: 'dense'

#### Windowing params #########################################################
window: 24
stride: 1

#### Model params #############################################################
# model:
#   name: grin
#   hparams:
#     hidden_size: 8
#     ff_size: 16
#     merge_mode: mean
# model:
#   name: rnni
#   hparams:
#     hidden_size: 64
#     cell: 'gru'
#     concat_mask: True
#     detach_input: False
#     fully_connected: False
#     state_init: 'zero'
    
model:
    name: mymodel
    hparams:
        hidden_size: 16
        embedding_size: 16
        n_conv_layers: 2
        cell: 'gru'
        concat_mask: True
        fully_connected: False
        # n_nodes: 207
        detach_input: False
        state_init: 'zero'
           


#### Training params ##########################################################
epochs: 10
patience: 3
batch_size: 8
grad_clip_val: 5
scale_target: True
optimizer:
  name: Adam
  hparams:
    lr: 0.001
    weight_decay: 0
lr_scheduler:
  name: CosineAnnealingLR
  hparams:
      eta_min: 0.0001
      T_max: ${ epochs }
